# Generated by Django 4.0.1 on 2022-09-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('middlename', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('regno', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('allocation', models.CharField(max_length=50)),
            ],
        ),
    ]
