# Generated by Django 4.0.1 on 2022-09-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldapplication',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
