# Generated by Django 4.0.1 on 2022-09-12 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field', '0003_alter_fieldapplication_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldapplication',
            name='allocation',
            field=models.CharField(choices=[('mbeya_cement', 'mbeya cement'), ('ally_rich', 'Ally Rich Ltd'), ('tra_mbeya', 'TRA Mbeya'), ('mzumbe_university', 'Mzumbe University')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldapplication',
            name='course',
            field=models.CharField(choices=[('computer_science', 'computer science'), ('computer_engineering', 'computer engineering'), ('data_science', 'data science'), ('cybersecurity', 'cybersecurity')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldapplication',
            name='department',
            field=models.CharField(choices=[('computer_science', 'computer science'), ('computer_engineering', 'computer engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldapplication',
            name='level',
            field=models.CharField(choices=[('certificate', 'CERTIFICATE'), ('diploma', 'DIPLOMA'), ('bachelor', 'BACHELOR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fieldapplication',
            name='year',
            field=models.CharField(choices=[('1st_year', '1st year'), ('2nd_year', '2nd year'), ('3rd_year', '3rd year')], max_length=50),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=500)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
