# Generated by Django 4.0.1 on 2022-09-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_alter_fieldapplication_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldapplication',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
