# Generated by Django 4.0.1 on 2022-09-13 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0005_fieldapplication_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldapplication',
            old_name='number',
            new_name='phone_number',
        ),
    ]
